CREATE TABLE MBTI_POST_MAS (
    ID SERIAL PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    CONTENT TEXT NOT NULL,
    AUTHOR VARCHAR(100) NOT NULL,
    MBTI_TYPE VARCHAR(4) NOT NULL,
    VIEWS INT DEFAULT 0,
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE MBTI_USER_MAS (
    ID SERIAL PRIMARY KEY,
    USERNAME VARCHAR(100) UNIQUE NOT NULL,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    MBTI_TYPE VARCHAR(4) NOT NULL,
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);